version: '3.8'

services:
  apm-webapi-development:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${DEFAULT_CONNECTION}
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - BUILD_CONFIGURATION=${BUILD_CONFIGURATION}
    
  